when:
  - event: pull_request
  - event: push

variables:
  - &node_image "docker.io/node:22-alpine"

steps:
  - name: install
    image: *node_image
    commands:
      - npm install
  - name: build
    image: *node_image
    commands:
      - npm run build
      - tar cvzf assets.tar.gz static/
  - name: upload
    image: "curlimages/curl:latest"
    commands:
      - 'curl --user NoUmlautsAllowed:$CODEBERG_REGISTRY_TOKEN --upload-file assets.tar.gz "https://codeberg.org/api/packages/NoUmlautsAllowed/generic/gocook/${CI_COMMIT_SHA}/assets.tar.gz"'
    secrets: [CODEBERG_REGISTRY_TOKEN]
    when:
      event: push
