when:
  event:
    - cron
    - push
    - pull_request
    - manual
  cron: renovate

steps:
  lint:
    image: renovate/renovate:latest
    pull: true
    commands:
      - renovate-config-validator
    environment:
      LOG_LEVEL: debug
    when:
      event: [push, pull_request]

  renovate:
    image: renovate/renovate:latest
    pull: true
    commands:
      - renovate $${CI_REPO}
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://codeberg.org
      RENOVATE_CONFIG_FILE: renovate.json
      LOG_LEVEL: debug
      GITHUB_COM_TOKEN:
        from_secret: github_com_token
      RENOVATE_TOKEN:
        from_secret: renovate_token
    when:
      - event: [cron, manual, push]
        cron: renovate
        branch: main
