name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.22.1

    - name: Get mockgen
      run: go get go.uber.org/mock/mockgen@v0.4.0
    
    - name: Generate
      run: go generate ./...
        

    - name: Lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.57.1

    - name: Build
      run: go build -v ./cmd/server

    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV }} #required
        file: coverage.txt #optional
        flags: unittests #optional
        fail_ci_if_error: true #optional (default = false)
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        path: server
