name: Node

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
    - run: npm i
    - run: npm run build
    
    - name: Upload a static assets
      uses: actions/upload-artifact@v4
      with:
        name: Static Assets
        path: static/
    
  
